### ISSUE TITLE
SUS

### ISSUE THREAD

**Issue by ST-Chara** [PCX-LK/Mindustry-src-v7#1]
SUSSY BAKA
SUSUSUSUSUSUSUSU

SUSSY BAKA SUSSSSY

**Comment by PCX-LK** [comment]
**A m o n g  U s**

**Comment by ST-Chara** [comment]
NGGYU

**Comment by PCX-LK** [comment]
> NGGYU

What the mean of "NGGYU" and "SUSSY"?????

**Comment by ST-Chara** [comment]
OPEN IT!
RIGHT NOW

**Comment by ST-Chara** [comment]
SSUUUUSSSYSYYYYYBAAKKKKAAAAAAAAA!!!!!!!!!!!!

**Comment by PCX-LK** [comment]
ur so stupid.....

**Comment by ST-Chara** [comment]
SUS

**Comment by PCX-LK** [comment]
But
### I
# R E F U S E

**Comment by ST-Chara** [comment]
NOOOOOOOOOO

**Comment by ST-Chara** [comment]
SUSSY

**Comment by PCX-LK** [comment]
> 搭嘎，口头哇路
![2022-05-03_21-52](https://user-images.githubusercontent.com/62936489/166466357-afaf3001-8ad9-4554-a9c7-b3e2a5a9caa6.png)
⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠

**Comment by ST-Chara** [comment]
NOOOOO

**Comment by ST-Chara** [comment]
![image](https://user-images.githubusercontent.com/74450074/166466779-35bfa094-3578-4b91-8e8d-51d4fd61e01d.png)

**Comment by PCX-LK** [comment]
笑使我屁股脱落

**Comment by PCX-LK** [comment]
Look this
![Sheet_1_2022-05-03](https://user-images.githubusercontent.com/62936489/166467800-3f24cfbd-a0aa-4e4c-bd5d-fc8398c79145.png)

**Comment by ST-Chara** [comment]
sus

**Comment by PCX-LK** [comment]
> sus

猜这是什么（（（
